version: '3.8'

services:
  db:
    image: docker.io/library/postgres:16
    container_name: podverdict-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: podverdict
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z

volumes:
  postgres_data: